import fs from "node:fs";
import path from "node:path";
import { classifyFiles } from "./classify.js";
import { inferConfig, isLegacyConfig } from "./config.js";
import { measureFiles } from "./counter.js";
import { listFiles } from "./files.js";
import { SCOPES } from "./scopes.js";
import type {
  AnalyzeRepositoryOptions,
  AreaDefinition,
  AreaResult,
  AreaUsage,
  BudgetViolation,
  CodeBudgetConfig,
  CodeBudgetReport,
  LegacyBudgetResult,
  LegacyCodeBudgetConfig,
} from "./types.js";

export interface CheckBudgetOptions
  extends Omit<AnalyzeRepositoryOptions, "config"> {}

export async function analyzeRepository(
  options: AnalyzeRepositoryOptions & {
    config: CodeBudgetConfig | LegacyCodeBudgetConfig;
  },
): Promise<CodeBudgetReport>;
export async function analyzeRepository(
  options: AnalyzeRepositoryOptions,
): Promise<CodeBudgetReport>;
export async function analyzeRepository(
  options: AnalyzeRepositoryOptions = {},
): Promise<CodeBudgetReport> {
  const cwd = path.resolve(options.cwd ?? process.cwd());
  const original = options.config ?? inferConfig();
  const legacy = isLegacyConfig(original);
  const config = legacy ? adaptLegacy(original) : original;
  const classification = classifyFiles(
    listFiles(cwd, config.files ?? "git-visible"),
    config.areas,
    config.ignore,
  );
  const areas: AreaResult[] = await Promise.all(
    config.areas.map(async (definition) => {
      const paths = classification.groups.get(definition.name) ?? [];
      return {
        definition,
        paths,
        usage: await measureFiles(cwd, paths, definition.kind, options.counter),
      };
    }),
  );
  const totals = {
    implementation: sumUsage(areas, "implementation"),
    tooling: sumUsage(areas, "tooling"),
    verification: sumUsage(areas, "verification"),
  };
  const configured = options.configured ?? options.config !== undefined;
  const violations = configured
    ? collectViolations(
        config,
        areas,
        classification,
        totals.implementation.codeLines,
      )
    : [];
  const budgets = legacy ? legacyResults(cwd, original, areas, violations) : [];
  const deprecations = legacy
    ? [
        "Configuration schema 0.0.1 is deprecated; migrate budgets to scope and areas.",
        ...(original.budgets.some(
          (budget) =>
            budget.maxBytes !== undefined || budget.maxFiles !== undefined,
        )
          ? [
              "maxBytes and maxFiles are legacy-only and are not generated by code-budget 0.1.",
            ]
          : []),
      ]
    : [];
  return {
    areas,
    budgets,
    configured,
    ...(options.configPath ? { configPath: options.configPath } : {}),
    cwd,
    diagnostics: {
      ancillary: classification.ancillary,
      deprecations,
      generatedVendorCandidates: classification.generatedVendorCandidates,
      metadata: classification.metadata,
      overlaps: classification.overlaps,
      unclassified: classification.unmatched,
    },
    inferred: !configured,
    ok: violations.length === 0,
    overlaps: classification.overlaps,
    schemaVersion: "1.0",
    scope: SCOPES[config.scope],
    totals,
    unmatched: classification.unmatched,
    violations,
  };
}

export async function checkBudgets(
  config: CodeBudgetConfig | LegacyCodeBudgetConfig,
  options: CheckBudgetOptions = {},
): Promise<CodeBudgetReport> {
  return analyzeRepository({ ...options, config, configured: true });
}

function adaptLegacy(config: LegacyCodeBudgetConfig): CodeBudgetConfig {
  return {
    areas: config.budgets.map((budget) => ({
      ...(budget.exclude ? { exclude: budget.exclude } : {}),
      include: budget.include,
      kind: "implementation" as const,
      name: budget.name,
    })),
    ...(config.files ? { files: config.files } : {}),
    ...(config.ignore ? { ignore: config.ignore } : {}),
    scope: "suite",
  };
}

function collectViolations(
  config: CodeBudgetConfig,
  areas: AreaResult[],
  classification: ReturnType<typeof classifyFiles>,
  implementationLoc: number,
): BudgetViolation[] {
  const violations: BudgetViolation[] = [];
  const limit = SCOPES[config.scope].implementationLoc;
  if (implementationLoc > limit) {
    violations.push({
      actual: implementationLoc,
      kind: "implementation-loc",
      limit,
      message: `Implementation LOC exceeds the ${config.scope} ceiling by ${implementationLoc - limit}.`,
      metric: "codeLines",
    });
  }
  for (const area of areas.filter(
    (value) => value.definition.kind === "review" && value.paths.length > 0,
  )) {
    violations.push({
      area: area.definition.name,
      kind: "review",
      message: `Area ${area.definition.name} requires explicit implementation, tooling, verification, or reasoned exclusion classification.`,
    });
  }
  for (const file of classification.unmatched) {
    violations.push({
      kind: "unclassified",
      message: `Source-like file is unclassified: ${file}`,
      path: file,
    });
  }
  for (const file of classification.generatedVendorCandidates) {
    violations.push({
      kind: "review",
      message: `Generated/vendor candidate requires explicit classification: ${file}`,
      path: file,
    });
  }
  for (const [file, matched] of Object.entries(classification.overlaps)) {
    violations.push({
      kind: "overlap",
      message: `File matches multiple areas (${matched.join(", ")}): ${file}`,
      path: file,
    });
  }
  return violations;
}

function legacyResults(
  cwd: string,
  config: LegacyCodeBudgetConfig,
  areas: AreaResult[],
  violations: BudgetViolation[],
): LegacyBudgetResult[] {
  const byName = new Map(areas.map((area) => [area.definition.name, area]));
  const results: LegacyBudgetResult[] = [];
  for (const definition of config.budgets) {
    const area = byName.get(definition.name)!;
    const usage = {
      bytes: area.paths.reduce(
        (total, file) => total + fs.statSync(path.join(cwd, file)).size,
        0,
      ),
      codeLines: area.usage.codeLines,
      files: area.usage.files,
    };
    const resultViolations: BudgetViolation[] = [];
    for (const [metric, limit] of [
      ["codeLines", definition.maxCodeLines],
      ["files", definition.maxFiles],
      ["bytes", definition.maxBytes],
    ] as const) {
      if (limit !== undefined && usage[metric] > limit) {
        const violation: BudgetViolation = {
          actual: usage[metric],
          budget: definition.name,
          kind: "legacy-budget",
          limit,
          message: `${definition.name} exceeds legacy ${metric} limit by ${usage[metric] - limit}.`,
          metric,
        };
        resultViolations.push(violation);
        violations.push(violation);
      }
    }
    results.push({
      definition,
      paths: area.paths,
      usage,
      violations: resultViolations,
    });
  }
  return results;
}

function sumUsage(
  areas: AreaResult[],
  kind: AreaDefinition["kind"],
): AreaUsage {
  const selected = areas.filter((area) => area.definition.kind === kind);
  const languages = new Map<string, { files: number; lines: number }>();
  for (const area of selected) {
    for (const language of area.usage.languages) {
      const current = languages.get(language.language) ?? {
        files: 0,
        lines: 0,
      };
      current.files += language.files;
      current.lines += language.lines;
      languages.set(language.language, current);
    }
  }
  return {
    binaryFiles: selected.reduce(
      (sum, area) => sum + area.usage.binaryFiles,
      0,
    ),
    codeLines: selected.reduce((sum, area) => sum + area.usage.codeLines, 0),
    files: selected.reduce((sum, area) => sum + area.usage.files, 0),
    languages: [...languages]
      .map(([language, usage]) => ({ language, ...usage }))
      .sort((a, b) => b.lines - a.lines),
    textFallbackFiles: selected.reduce(
      (sum, area) => sum + area.usage.textFallbackFiles,
      0,
    ),
  };
}
